# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  Deal.create(
    id: 100,
    name: "iPhone 6 16GB",
    description: "4.7-inch Retina HD display. A8 chip with 64-bit desktop-class architecture. 6.9mm thin.",
    price: 20,
    image: nil,
    threshold: 40,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 101,
    name: "Xbox One",
    description: "500GB Hard Drive",
    price: 10,
    image: nil,
    threshold: 40,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 102,
    name: "Samsung Galaxy S6",
    description: "Octa-core 32GB Unlocked GSM Android Smartphone",
    price: 20,
    image: nil,
    threshold: 40,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSrPqmwtGp5eg-uKVumt3ZDvTrm_AhhTPL9_6I_l8URZOISHvP-Q3BWbqcGNNV3DpJ-mv_Sa3II&usqp=CAY",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 103,
    name: "PlayStation 4",
    description: "PlayStation 4 Console",
    price: 15,
    image: nil,
    threshold: 30,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcS4FXyAdBuqnhkpJpb_iy_k5a80q0AGGYojv5uX6SE1aM0n-saxqlwOqq62cnF-trWoKRoLh3CI0w&usqp=CAY",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 104,
    name: "Bose SoundLink Mini",
    description: "Mini Speaker - Portable - Wireless - Silver",
    price: 5,
    image: nil,
    threshold: 35,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTVGvq7YL0ed_Jlght_hlLaUhD4E4Pd8NLBkBMT2JVmFRQgqHghSLlzJqpeC7TXAYrHKiLjxw3a&usqp=CAY",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 105,
    name: "Nintendo Wii U",
    description: "Nintendo Wii U - 32 GB - Black - includes Nintendo Land, Super Mario 3D World",
    price: 14,
    image: nil,
    threshold: 20,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTu76Mj9GG0A7WmbF2E5CtEm4dDuqMLzHJivMcfP1Fytv45ofQExiqEXCZiHbcNw98Ue8nU1ng&usqp=CAY",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 106,
    name: "Pebble Watch",
    description: "Pebble Steel Smart Watch for iPhone and Android Devices (Black Matte)",
    price: 5,
    image: nil,
    threshold: 35,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "http://images17.newegg.com/is/image/newegg/86-712-001-Z01?$S300W$",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 107,
    name: "Call of Duty: Black Ops III",
    description: "Call of Duty: Black Ops III - Digital Deluxe Edition - PlayStation 4 ",
    price: 8,
    image: nil,
    threshold: 15,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "http://ecx.images-amazon.com/images/I/41pX811Ke1L._AA160_.jpg",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 108,
    name: "Pebble Watch",
    description: "Pebble - Time 22mm Smartwatch for Most Apple® iOS and Android Devices - White",
    price: 10,
    image: nil,
    threshold: 24,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "http://pisces.bbystatic.com/image2/BestBuy_US/images/products/8186/8186014_ra.jpg;canvasHeight=300;canvasWidth=210",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 109,
    name: "FIFA 15",
    description: "FIFA 15 (Xbox One)",
    price: 3,
    image: nil,
    threshold: 12,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "http://scene7.targetimg1.com/is/image/Target/15421763?wid=480&hei=480",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )


  Deal.create(
    id: 110,
    name: "Marshall Headset",
    description: "Marshall Audio Monitor Over-Ear Headphones (Black)",
    price: 10,
    image: nil,
    threshold: 17,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "http://static.bhphoto.com/images/images500x500/marshall_audio_4090800_monitor_headphone_black_1383751551000_1013319.jpg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

    Deal.create(
      id: 111,
      name: "Razer Blade Pro",
      description: "Razer Blade Pro R5 17.3in Gaming Laptop",
      price: 100,
      image: nil,
      threshold: 28,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRlQiNXCetg-qVtcdj6owx-RFo0aAU4KOEl1svpPrv1ABuGX0hV-C5C8sAqHvZjd5NaIFEpspA&usqp=CAE",
      product_type: "Video Games",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 112,
      name: "iPhone 6 16GB",
      description: "4.7-inch Retina HD display. A8 chip with 64-bit desktop-class architecture. 6.9mm thin.",
      price: 40,
      image: nil,
      threshold: 20,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
      product_type: "Electronics",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 113,
      name: "CyberpowerPC",
      description: "CyberpowerPC Gaming Desktop AMD Configurator Cyber AMD Config",
      price: 20,
      image: nil,
      threshold: 30,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT4aDqY6QzpMRcXaK4Oyr9T8byROYeknH5i29b8h1d36KsBZkg4AVxhtOrYob965V2L_LYF41S6&usqp=CAE",
      product_type: "Video Games",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 114,
      name: "MacBook Air 13.3in",
      description: "Apple MacBook Air 13.3in Notebook - Core i5 1.6 GHz - 4 GB RAM - 128 GB SSD - Silver",
      price: 20,
      image: nil,
      threshold: 45,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRedBfDTi5xdJEyykRNAouQU1FviW0cl-yVnmblR_JIbL-k9LPEAg",
      product_type: "Electronics",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 115,
      name: "Xbox One",
      description: "500GB Hard Drive",
      price: 40,
      image: nil,
      threshold: 10,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
      product_type: "Video Games",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )
